# Generated by Django 3.1.3 on 2020-11-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DISABLED', 'DISABLED'), ('ARCHIVED', 'ARCHIVED'), ('DELETED', 'DELETED')], max_length=10),
        ),
    ]
