# Generated by Django 3.1.3 on 2020-11-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=models.CharField(choices=[('NOT STARTED', 'NOT STARTED'), ('RUNNING', 'RUNNING'), ('IN REVIEW', 'IN REVIEW'), ('REVIEWED', 'REVIEWED'), ('CLOSED', 'CLOSED')], max_length=20),
        ),
    ]
